name:                atcoder
version:             0.1.0.0
github:              "minoki/atcoder"
license:             BSD3
author:              "ARATA Mizuki"
maintainer:          "minorinoki@gmail.com"
copyright:           "2019 ARATA Mizuki"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/minoki/atcoder#readme>

dependencies:
- base >= 4.7 && < 5
- array
- vector
- containers
- mtl

ghc-options:
# Maximum heap size: 1GiB
- -with-rtsopts=-M1G

executables:
  tdpc-a:
    main:                Main.hs
    source-dirs:         tdpc-a

  tdpc-b:
    main:                Main.hs
    source-dirs:         tdpc-b

  tdpc-c:
    main:                Main.hs
    source-dirs:         tdpc-c

  tdpc-d:
    main:                Main.hs
    source-dirs:         tdpc-d

  tdpc-e:
    main:                Main.hs
    source-dirs:         tdpc-e

  tdpc-f:
    main:                Main.hs
    source-dirs:         tdpc-f

  tdpc-g:
    main:                Main.hs
    source-dirs:         tdpc-g
    dependencies:
      - bytestring

  tdpc-h:
    main:                Main.hs
    source-dirs:         tdpc-h

  abc032-d:
    main:                Main.hs
    source-dirs:         abc032-d
