name:                atcoder
version:             0.1.0.0
github:              "minoki/atcoder"
license:             BSD3
author:              "ARATA Mizuki"
maintainer:          "minorinoki@gmail.com"
copyright:           "2019 ARATA Mizuki"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/minoki/atcoder#readme>

dependencies:
- base >= 4.7 && < 5
- array
- vector
- containers
- mtl
- bytestring

ghc-options:
# Maximum heap size: 1GiB
- -with-rtsopts=-M1G

library:
  source-dirs: lib

executables:
  tdpc-a:
    main:                Main.hs
    source-dirs:         tdpc-a

  tdpc-b:
    main:                Main.hs
    source-dirs:         tdpc-b

  tdpc-c:
    main:                Main.hs
    source-dirs:         tdpc-c

  tdpc-d:
    main:                Main.hs
    source-dirs:         tdpc-d

  tdpc-e:
    main:                Main.hs
    source-dirs:         tdpc-e

  tdpc-f:
    main:                Main.hs
    source-dirs:         tdpc-f

  tdpc-g:
    main:                Main.hs
    source-dirs:         tdpc-g

  tdpc-h:
    main:                Main.hs
    source-dirs:         tdpc-h

  abc032-d:
    main:                Main.hs
    source-dirs:         abc032-d

  agc031-a:
    main:                Main.hs
    source-dirs:         agc031-a

  agc031-b:
    main:                Main.hs
    source-dirs:         agc031-b

  agc031-c:
    main:                Main.hs
    source-dirs:         agc031-c

  agc031-d:
    main:                Main.hs
    source-dirs:         agc031-d

  caddi2019-a:
    main:                Main.hs
    source-dirs:         caddi2019-a

  agc032-a:
    main:                Main.hs
    source-dirs:         agc032-a

  agc032-b:
    main:                Main.hs
    source-dirs:         agc032-b

  abc122-a:
    main:                Main.hs
    source-dirs:         abc122-a

  abc122-b:
    main:                Main.hs
    source-dirs:         abc122-b

  abc122-c:
    main:                Main.hs
    source-dirs:         abc122-c

  abc122-d:
    main:                Main.hs
    source-dirs:         abc122-d

  abc121-a:
    main:                Main.hs
    source-dirs:         abc121-a

  abc121-b:
    main:                Main.hs
    source-dirs:         abc121-b

  abc121-c:
    main:                Main.hs
    source-dirs:         abc121-c

  abc121-d:
    main:                Main.hs
    source-dirs:         abc121-d

  abc120-a:
    main:                Main.hs
    source-dirs:         abc120-a

  abc120-b:
    main:                Main.hs
    source-dirs:         abc120-b

  abc120-c:
    main:                Main.hs
    source-dirs:         abc120-c

  abc120-d:
    main:                Main.hs
    source-dirs:         abc120-d

  dp-a:
    main:                Main.hs
    source-dirs:         dp-a

  dp-b:
    main:                Main.hs
    source-dirs:         dp-b

  dp-c:
    main:                Main.hs
    source-dirs:         dp-c

  dp-d:
    main:                Main.hs
    source-dirs:         dp-d

  dp-e:
    main:                Main.hs
    source-dirs:         dp-e

  exawizards2019-a:
    main:                Main.hs
    source-dirs:         exawizards2019-a

  exawizards2019-b:
    main:                Main.hs
    source-dirs:         exawizards2019-b

  exawizards2019-c:
    main:                Main.hs
    source-dirs:         exawizards2019-c

  exawizards2019-d:
    main:                Main.hs
    source-dirs:         exawizards2019-d

  exawizards2019-e:
    main:                Main.hs
    source-dirs:         exawizards2019-e

  agc023-a:
    main:                Main.hs
    source-dirs:         agc023-a
