name:                atcoder
version:             0.1.0.0
github:              "minoki/my-atcoder-solutions"
license:             BSD3
author:              "ARATA Mizuki"
maintainer:          "minorinoki@gmail.com"
copyright:           "2019 ARATA Mizuki"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/minoki/my-atcoder-solutions#readme>

dependencies:
- base >= 4.7 && < 5
- array
- vector
- containers
- mtl
- bytestring
- text
- deepseq
- primitive
- reflection
- unboxing-vector
- vector-algorithms
- QuickCheck
- arithmoi

ghc-options:
# Maximum heap size: 1GiB
- -with-rtsopts=-M1G
- -dynamic

library:
  source-dirs: lib

tests:
  doctest:
    main: doctests.hs
    dependencies:
    - doctest

# executables:
#   foo:
#     main : Main.hs
#     source-dirs: foo
